algoritmo "semnome"
//5. Faça um programa que receba três notas e seus respectivos pesos, calcule e mostre a média ponderada:
var
    n1, n2, n3, m: real


inicio

      escreva("Digite a Primeira Nota: ")
      leia(n1)
      escreva("Digite a Segunda Nota: ")
      leia(n2)
      escreva("Digite a Terceira Nota: ")
      leia(n3)
      m <-(n1+n2+n3)/3;
      escreva("A Média é: ",m)
      



fimalgoritmo
